version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/livraria_new
hooks:
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
    - location: scripts/apache_config.sh
      timeout: 300
      runas: root
    - location: scripts/app_config.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
